#!/bin/bash

# Control automatic fan adjustment for desktop.


sudo pacman -Syu lm_sensors dmidecode psensor -y

sudo touch /etc/modules-load.d/nct6775.conf
sudo echo "nct6775" >> /etc/modules-load.d/nct6775.conf
sudo modprobe nct6775

test
asd